# Generated by Django 5.0.7 on 2024-07-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.CharField(max_length=60),
        ),
    ]
