# Generated by Django 5.0.7 on 2024-07-20 11:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_status_alter_department_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('IN', 'Internship'), ('FL', 'Freelance')], default='FT', max_length=2)),
                ('experience', models.CharField(choices=[('0-1', '0-1 years'), ('1-2', '1-2 years'), ('2-3', '2-3 years'), ('3-4', '3-4 years'), ('4-5', '4-5 years'), ('5+', '5+ years')], max_length=3)),
                ('job_description', models.TextField()),
                ('skills_required', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('IN', 'Inactive')], default='AC', max_length=2)),
            ],
        ),
    ]
