# Generated by Django 5.0.7 on 2024-07-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full time', 'Full Time'), ('part time', 'Part Time'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full time', max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=15),
        ),
    ]
