# Generated by Django 5.0.7 on 2024-07-20 12:21

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_job_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('experience', models.CharField(choices=[('0-1', '0-1 years'), ('1-2', '1-2 years'), ('2-3', '2-3 years'), ('3-4', '3-4 years'), ('4-5', '4-5 years'), ('5+', '5+ years')], max_length=3)),
                ('skills', ckeditor.fields.RichTextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
            ],
        ),
    ]
